# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'TechnicalChallenge' do
pod "AFNetworking", "~> 2.0"
pod "SDWebImage", "~>3.7"
end

target 'TechnicalChallengeTests' do

end

